spring.thymeleaf.cache=true
spring.h2.console.enabled=false
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
server.forward-headers-strategy=framework
server.servlet.session.cookie.secure=true
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false
logging.level.org.hibernate.SQL=OFF
app.demo.seed-enabled=false
