spring.thymeleaf.cache=true
spring.h2.console.enabled=false
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
server.forward-headers-strategy=framework
server.tomcat.use-relative-redirects=true
server.servlet.session.cookie.secure=true
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false
logging.level.org.hibernate.SQL=OFF
app.demo.seed-enabled=false
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=2
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
